<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="tgt"
    nsURI="http://example.org/enum-datatype/tgt"
    nsPrefix="tgt">
  <eClassifiers xsi:type="ecore:EEnum" name="TargetKind">
    <eLiterals name="FIRST" value="0" literal="first"/>
    <eLiterals name="SECOND" value="1" literal="second"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TargetCode"
      instanceClassName="java.lang.String" serializable="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Result">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="targetInvariant"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="targetInvariant" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind"
        lowerBound="1" eType="#//TargetKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code"
        lowerBound="1" eType="#//TargetCode"/>
  </eClassifiers>
</ecore:EPackage>
