Library_min = 1
Library_max = 1
Book_min = 2
Book_max = 2
Member_min = 3
Member_max = 3
Holdings_min = 0
Holdings_max = -1
Membership_min = 0
Membership_max = -1
Loan_min = 5
Loan_max = -1
Integer_min = 1
Integer_max = 1
String_min = 1
String_max = 6
Library_uniqueBookTitles = active
Book_positiveCopies = active
Book_notOverLent = active
Member_borrowsFromOwnLibrary = active
Library_hasAtLeastOneBook = active
